[package]
name = "nanotimes"
version = "0.2.0"
authors = ["Angel Angelov <aangeloo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "~2.33.3"
kseq = "0.5.3"
regex = "1"
chrono = "0.4"